### ISSUE TITLE
[Feedback]: VerifyURLs don't function for verification

### ISSUE THREAD

**Issue by randomforestier** [matter-labs/zksync-docs#135]
### Page

https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-verify

### Description

I have found a related issue: https://github.com/matter-labs/hardhat-zksync/issues/1024

The documentation contains verifyURLs like https://sepolia.explorer.zksync.io/contract_verification which result in the following error when attempting to verify the contract:
"Deployment failed: ZkSyncVerifyPluginError: Solidity compiler you used to compile the contract is not currently supported by zkSync block explorer!" -- which makes no sense since I have tried every and each version of solc and solidity I could. The verifyURL shall be "https://explorer.sepolia.era.zksync.dev/contract_verification".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dckesso** [comment]
The error message suggests that the Solidity compiler you have been using is not currently supported by zkSync block explorer, causing the deployment to fail. To resolve this issue, you can try the following solutions:

Check the version of Solidity you are using and make sure it is supported by zkSync block explorer. You can refer to the zkSync documentation or contact their support team for more information on the supported versions.
Try using a different version of the Solidity compiler. If you have already tried every version you can find, you can try using online Solidity compilers like Remix to compile your contract and then try deploying it again.
Check if the URL you are using to verify the contract is correct. The error message suggests that the URL you are using may not be correct. You can try using the URL "https://explorer.sepolia.era.zksync.dev/contract_verification" instead, as suggested, and see if it resolves the issue.
Check for any other errors in your contract code that could be causing the deployment to fail. You can use tools like the Solidity compiler or other debugging tools to identify and fix any errors in your code.

If none of these solutions work, you can contact zkSync support for further assistance in resolving the issue.
