### ISSUE TITLE
[Feature]: System Contracts deployment addresses

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/zksync-docs#140]
### Description

Right now, it's really difficult to find the system contracts deployment addresses, please add them to the documentation for testing. 

### Rationale

When I test my smart contracts, I want to make sure I'm interacting with the correct addresses. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsacoyote** [comment]
Reopening since the latest PR does not fully cover the extent of the issue posted.

**Comment by dutterbutter** [comment]
Hey @PatrickAlphaC 👋 

https://github.com/matter-labs/zksync-docs/pull/240 adds these addresses to the docs. Always appreciate the detailed necessitates you find 👏  Keep them coming 💪

**Comment by PatrickAlphaC** [comment]
big!
