### ISSUE TITLE
[Bug]: Add ZKsync to MetaMask buttons do not work

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/zksync-docs#227]
### What happened?

If you go to `Connect to ZKsync Era` page and select the "Add ZKsync to MetaMask" buttons nothing happens. MetaMask window is never prompted. 

### What did you expect to happen?

MetaMask network page to appear with all relevant network info for ZKsync Sepolia to be included. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahschwartz** [comment]
I'm not able to reproduce, both of the buttons work for me. What browser and version of Metamask are you using?

**Comment by dutterbutter** [comment]
Closing as it was my experimental browser I was using.
