### ISSUE TITLE
[Feedback]: ABI Bridge Ethereum->ZkSync Era

### ISSUE THREAD

**Issue by Mukumays** [matter-labs/zksync-docs#262]
### Page

https://docs.zksync.io/build/zksync-cli/reading-transaction-data

### Description

Good day, I've been reading for a long time, studying your documentation, but I can't find the ABI for the ZkSync Portal Bridge, I want to make a transaction using requestL2Transaction with the signature (0xeb672419), but it just doesn't exist...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MexicanAce** [comment]
Hi @Mukumays , all contract addresses can be found here : https://docs.zksync.io/build/developer-reference/addresses/zk-chain-addresses

I believe you're looking for this contract: https://etherscan.io/address/0xD7f9f54194C633F36CCD5F3da84ad4a1c38cB2cB#code

Also, for awareness, [ZKsync Era recently went through a migration](https://docs.zksync.io/build/developer-reference/era-contracts/l1-ecosystem-contracts#migrating-direct-interaction-with-era) to become a ZK Chain, and thus `requestL2Transaction` is now replaced with `requestL2TransactionTwoBridges`

**Comment by Mukumays** [comment]
[{"inputs":[{"internalType":"address","name":"_logic","type":"address"},{"internalType":"address","name":"admin_","type":"address"},{"internalType":"bytes","name":"_data","type":"bytes"}],"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"previousAdmin","type":"address"},{"indexed":false,"internalType":"address","name":"newAdmin","type":"address"}],"name":"AdminChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"beacon","type":"address"}],"name":"BeaconUpgraded","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"},{"stateMutability":"payable","type":"receive"}]

But this contract also has neither this **requestL2Transaction** nor any other function in the ABI **requestL2TransactionTwoBridges**

**Comment by Mukumays** [comment]
I am very interested in your network, maybe there are ways to help you in development?

**Comment by MexicanAce** [comment]
Apologies, I posted a link to the `SharedBridge` contract and not the `BridgeHub`. However, these are both proxies (as seen by the ABIs), so you will want to look at the proxy contract for the final ABI: https://etherscan.io/address/0x303a465B659cBB0ab36eE643eA362c509EEb5213#writeProxyContract

**Comment by Mukumays** [comment]
Great! I'll try this tonight, thanks for the help. I hope I can make the transaction :)
