### ISSUE TITLE
[Feedback]: ZKsync Era Extension Simulation (verbatim) documentation is identical to (call)

### ISSUE THREAD

**Issue by giovannidisiena** [matter-labs/zksync-docs#269]
### Page

https://docs.zksync.io/zk-stack/components/compiler/specification/instructions/extensions/verbatim

### Description

The [ZKsync Era Extension Simulation (verbatim)](https://docs.zksync.io/zk-stack/components/compiler/specification/instructions/extensions/verbatim) documentation appears to have erroneously copied the entirety of the [ZKsync Era Extension Simulation (call)](https://docs.zksync.io/zk-stack/components/compiler/specification/instructions/extensions/call) content. In ZKsync Era, verbatim builtin functions are used to to access custom opcodes that are not known to the Yul compiler. While this achieves a similar goal to the overloading of the `CALL` instruction, the two methods are distinct and should be documented as such.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dimazhornyk** [comment]
Hi! Thanks for pointing this out, it was indeed miscopied. Our compiler team will have a look
I will write back here when it is fixed

**Comment by hedgar2017** [comment]
@giovannidisiena the docs have been moved [here](https://matter-labs.github.io/era-compiler-solidity/latest/06-eravm-extensions.html)!
We'll soon change the references from the main doc.
